// Powered by NyphexAI
// Developed by Hikaru (i@rua.moe)
// Copyright (C) 2026 Hikaru Chang <i@rua.moe>
// SPDX-License-Identifier: GPL-3.0-or-later
'use strict';
'require view';
'require dom';
'require poll';
'require rpc';
'require ui';

var callStatus = rpc.declare({
	object: 'kddi',
	method: 'status'
});

var callAction = rpc.declare({
	object: 'kddi',
	method: 'action',
	params: [ 'name' ]
});

var callLog = rpc.declare({
	object: 'kddi',
	method: 'log',
	params: [ 'lines' ],
	expect: { log: '' }
});

function badge(ok, yes, no) {
	return E('span', {
		'class': 'label',
		'style': 'background-color:%s;color:#fff;padding:2px 6px;border-radius:3px'
			.format(ok ? '#5b9a4d' : '#a33')
	}, ok ? yes : no);
}

function table(rows) {
	return E('table', { 'class': 'table' }, rows.filter(function(r) {
		return r != null;
	}).map(function(r) {
		return E('tr', { 'class': 'tr' }, [
			E('td', { 'class': 'td left', 'width': '35%' }, [ r[0] ]),
			E('td', { 'class': 'td left' }, [ r[1] ])
		]);
	}));
}

function duration(sec) {
	sec = parseInt(sec) || 0;
	if (sec <= 0)
		return '-';

	var d = Math.floor(sec / 86400),
	    h = Math.floor(sec % 86400 / 3600),
	    m = Math.floor(sec % 3600 / 60),
	    s = sec % 60;

	return (d ? '%dd '.format(d) : '') + '%02d:%02d:%02d'.format(h, m, s);
}

function renderSummary(st) {
	return table([
		[ _('Plugin'), badge(st.enabled, _('enabled'), _('disabled')) ],
		[ _('Protocol handler'), st.packages
			? badge(st.packages.proto_registered, _('registered in netifd'),
				st.packages.proto ? _('installed, netifd restart pending') : _('missing'))
			: '-' ],
		[ _('WAN device'), st.device || '-' ],
		[ _('MAC address'), E('span', {}, [
			E('code', {}, st.macaddr_current || '-'),
			' ',
			st.macaddr
				? badge(st.macaddr_applied, _('HGW address active'), _('does not match %s').format(st.macaddr))
				: badge(false, '', _('no HGW address configured'))
		]) ]
	]);
}

function renderWan(st) {
	var w = st.wan || {};

	if (!w.configured)
		return E('p', {}, _('Interface %s does not exist yet.').format(w.name || 'wan'));

	return table([
		[ _('Status'), badge(w.up, _('connected'), _('not connected')) ],
		[ _('Protocol'), w.proto || '-' ],
		[ _('IPv4 address'), w.ipaddr ? '%s/%d'.format(w.ipaddr, w.mask) : '-' ],
		[ _('Gateway'), w.gateway || '-' ],
		[ _('DNS servers'), (w.dns && w.dns.length) ? w.dns.join(', ') : '-' ],
		[ _('DHCP server'), w.server || '-' ],
		[ _('Lease time'), w.leasetime ? duration(w.leasetime) : '-' ],
		[ _('Connected'), duration(w.uptime) ]
	]);
}

function renderWan6(st) {
	var w = st.wan6, m = st.map;

	if (!w)
		return E('p', {}, _('IPv6 is disabled in the plugin settings.'));

	if (!w.configured)
		return E('p', {}, _('Interface %s does not exist yet.').format(w.name || 'wan6'));

	return table([
		[ _('Status'), badge(w.up, _('connected'), _('not connected')) ],
		[ _('Delegated prefix'), (w.prefix && w.prefix != '/') ? w.prefix : '-' ],
		[ _('Address'), w.address || '-' ],
		[ _('DNS servers'), (w.dns && w.dns.length) ? w.dns.join(', ') : '-' ],
		[ _('Connected'), duration(w.uptime) ],
		(m && m.present)
			? [ _('IPv4 over IPv6'), '%s (%s): %s'.format(m.name, m.proto || '-', m.ipaddr || _('no address')) ]
			: [ _('IPv4 over IPv6'), _('no S46 rule received') ]
	]);
}

function renderDot1x(st) {
	var d = st.dot1x || {};

	if (!d.enabled)
		return E('p', {}, _('802.1X authentication is disabled.'));

	return table([
		[ _('Supplicant'), badge(d.running, _('running'), _('stopped')) ],
		[ _('EAP method'), d.eap || '-' ],
		[ _('State'), d.state || (d.cli_installed ? _('unknown') : _('install wpa-cli to read the state')) ],
		[ _('EAP state'), d.eap_state || '-' ],
		[ _('Port status'), d.port_status || '-' ]
	]);
}

function renderFingerprint(st) {
	var f = st.fingerprint || {};

	return table([
		[ _('DHCPv4 vendor class (60)'), E('code', {}, '%s (%s)'.format(f.vendorid || '-', f.vendorid_hex || '')) ],
		[ _('DHCPv4 request list (55)'), E('code', {}, f.prl || '-') ],
		[ _('DHCPv4 client ID (61)'), _('not sent') ],
		[ _('DHCPv4 host name (12)'), _('not sent') ],
		[ _('DHCPv4 lease request (51)'), '%d s'.format(f.leasetime || 0) ],
		[ _('DHCPv6 DUID'), E('code', {}, f.duid || _('generated by netifd')) ],
		[ _('DHCPv6 IA_PD IAID'), E('code', {}, f.iaid || '-') ],
		[ _('DHCPv6 client FQDN (39)'), E('code', {}, '%s (%s)'.format(f.model || '-', f.fqdn_hex || '')) ]
	]);
}

return view.extend({
	handleAction: function(name) {
		return callAction(name).then(function(res) {
			res = res || {};
			ui.addNotification(null,
				E('pre', { 'style': 'white-space:pre-wrap;margin:0' },
					res.stdout || (res.code === 0 ? _('Done.') : _('Failed.'))),
				res.code === 0 ? 'info' : 'warning');
		}).catch(function(err) {
			ui.addNotification(null, E('p', {}, err.message), 'error');
		});
	},

	load: function() {
		return Promise.all([
			callStatus(),
			callLog(100)
		]);
	},

	pollData: function(container) {
		var self = this;

		poll.add(function() {
			return Promise.all([ callStatus(), callLog(100) ]).then(function(data) {
				dom.content(container, self.renderContent(data[0] || {}, data[1] || ''));
			});
		}, 5);
	},

	renderContent: function(st, log) {
		return [
			E('h3', {}, _('Overview')),
			renderSummary(st),

			E('h3', {}, _('IPv4 (%s)').format((st.wan || {}).name || 'wan')),
			renderWan(st),

			E('h3', {}, _('IPv6 (%s)').format((st.wan6 || {}).name || 'wan6')),
			renderWan6(st),

			E('h3', {}, _('802.1X')),
			renderDot1x(st),

			E('h3', {}, _('Fingerprint sent to KDDI')),
			renderFingerprint(st),

			E('h3', {}, _('Log')),
			E('pre', {
				'class': 'cbi-section',
				'style': 'white-space:pre-wrap;max-height:20em;overflow:auto'
			}, log || _('No related log messages yet.'))
		];
	},

	render: function(data) {
		var st = data[0] || {},
		    log = data[1] || '',
		    container = E('div', {}, this.renderContent(st, log));

		this.pollData(container);

		return E('div', { 'class': 'cbi-map' }, [
			E('h2', {}, _('KDDI au HIKARI')),
			E('div', { 'class': 'cbi-map-descr' },
				_('Status of the WAN connection that impersonates a KDDI home gateway.')),

			E('div', { 'class': 'cbi-section' }, [
				E('div', { 'class': 'cbi-page-actions', 'style': 'text-align:left' }, [
					E('button', {
						'class': 'btn cbi-button cbi-button-apply',
						'click': ui.createHandlerFn(this, 'handleAction', 'apply')
					}, _('Write network config')),
					' ',
					E('button', {
						'class': 'btn cbi-button cbi-button-action',
						'click': ui.createHandlerFn(this, 'handleAction', 'renew')
					}, _('Renew lease')),
					' ',
					E('button', {
						'class': 'btn cbi-button cbi-button-action',
						'click': ui.createHandlerFn(this, 'handleAction', 'dot1x_reauth')
					}, _('Re-authenticate 802.1X')),
					' ',
					E('button', {
						'class': 'btn cbi-button cbi-button-action',
						'click': ui.createHandlerFn(this, 'handleAction', 'restart')
					}, _('Restart service')),
					' ',
					E('button', {
						'class': 'btn cbi-button cbi-button-reset',
						'click': ui.createHandlerFn(this, 'handleAction', 'restore')
					}, _('Restore network backup'))
				])
			]),

			container
		]);
	},

	handleSave: null,
	handleSaveApply: null,
	handleReset: null
});
